name: Staging Deployment

on:
  push:
    branches: [ bref-staging ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug
      - name: Setup Laravel Sail
        uses: docker://laravelsail/php83-composer:latest
      - name: Setup nova credentials
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_LICENSE_KEY }}
      - name: Install Project Dependencies
        run: composer update
      - name: Install Project Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Setup env file
        run: cp .env.ci .env
      - name: Start Sail       
        run: vendor/bin/sail up -d
      - name: Sleep
        uses: juliangruber/sleep-action@v2.0.3
        with:
          time: 20s
      - name: Run database migrations
        run: vendor/bin/sail artisan migrate --force
      - name: Check test coverage
        run: vendor/bin/sail artisan test --coverage --min=100.0
      - name: Run browser tests
        run: |
          vendor/bin/sail dusk | tee dusk-output.log
          if grep -q "FAIL" dusk-output.log; then
            echo "Detected test failures in Dusk output."
            exit 1
          fi
          echo "All Dusk tests passed. Forcing exit code 0 due to Dusk/Sail CI quirk."
          exit 0
      - name: Stop Sail       
        run: vendor/bin/sail down
